### ISSUE TITLE
Cache bitbucket server responses

### ISSUE THREAD

**Issue by viceice** [oeph/verdaccio-bitbucket-server#11]
With auth enabled for access packages, this plugin add a lot of load to bitbucket.

This plugin should cache the responses at least for a configurable amount of time.

**Comment by oeph** [comment]
Yes, this is a feature I also want to add. Do you want to do a PR?

**Comment by viceice** [comment]
Yes, i would use [axios-extensions#throttleadapterenhancer](https://github.com/kuitos/axios-extensions#throttleadapterenhancer) or should we manage cache ourself?

**Comment by viceice** [comment]
No, can't use the extensions, it will not handle `auth`, so i'll use [lru-cache](https://www.npmjs.com/package/lru-cache).

**Comment by oeph** [comment]
@ViceIce do you have any updates?

**Comment by viceice** [comment]
Sorry, I'm currently on holiday. Trying to solve afterwards. 😁

**Comment by oeph** [comment]
No problem! Have great time ;)
