### ISSUE TITLE
Logged errors should be sanitized 

### ISSUE THREAD

**Issue by viceice** [oeph/verdaccio-bitbucket-server#8]
Currently logged error can leak user passwords.

Those values should be replaced by `***` or something like that.

**Comment by oeph** [comment]
You are right! :+1:  I will look into it, but only have the time this weeked. If you want, you could also prepare a PR

**Comment by oeph** [comment]
Fixed with v1.2.6

**Comment by viceice** [comment]
No chance to send a pr, you've got it to fast. 😅

**Comment by oeph** [comment]
Yeah, had some spare minutes today 😅
